# Discover on demand

name: discover-ondemand

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  run-discover-ondemand:
    uses: GEOS-ESM/CI-workflows/.github/workflows/geosongpu-ondemand.yml@refs/heads/remotes/origin/project/geosongpu