# Discover on demand
name: Discover CI On PR Comment

on:
  issue_comment:
      types: [created]

defaults:
  run:
    shell: bash

jobs:
  check-valid-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    outputs:
      experiment-name: ${{ steps.extractor.outputs.EXP_NAME }}
      experiment-action: ${{ steps.extractor.outputs.EXP_ACTION }}
    steps:
      - name: Extract command
        id: extractor
        if: contains(github.event.comment.body, '/discover-ci')
        shell: bash
        run: |
          echo Launching Discover CI: ${{github.event.comment.body}}
          BODY="${{github.event.comment.body}}"
          EXP_NAME_DIRTY=${BODY#*experiment-name=}
          echo "EXP_NAME=${EXP_NAME_DIRTY%% *}" >> "$GITHUB_OUTPUT"
          EXP_ACTION_DIRTY=${BODY#*experiment-action=}
          echo "EXP_ACTION=${EXP_ACTION_DIRTY%% *}" >> "$GITHUB_OUTPUT"

  run-discover-ondemand:
    needs: check-valid-comment
    runs-on: ubuntu-latest
    outputs:
      is_ok: ${{ steps.check.outputs.OK }}
    steps:
      - name: check
        id: check
        run: |
          echo ${{ needs.check-valid-comment.outputs.experiment-name }} ${{ needs.check-valid-comment.outputs.experiment-action }}
          echo "OK=True" >> "$GITHUB_OUTPUT"

# run-discover-ondemand:
#   needs: check-valid-comment
#   if: ${{ steps.run-discover-ondemand.outcome == 'success' }}
#   uses: GEOS-ESM/CI-workflows/.github/workflows/geosongpu-ondemand.yml@project/geosongpu
#   with:
#     experiment_name:   ${{ inputs.experiment_name }}
#     experiment_action: ${{ inputs.experiment_action }}

  respond-to-comment:
    needs: run-discover-ondemand
    runs-on: ubuntu-latest
    steps:
      - name: Message success
        if: ${{ needs.run-discover-ondemand.outputs.is_ok == 'True' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Discover check succeeded! ✅',
            });          
      - name: Message failure
        if: ${{ needs.run-discover-ondemand.outputs.is_ok != 'True' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Discover CI failed! ❌',
            }); 
