# Discover's CI check

name: Discover Nightly Physics Standalone Validation

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

defaults:
  run:
    shell: bash

jobs:
  run-discover-ondemand:
    uses: GEOS-ESM/CI-workflows/.github/workflows/geosongpu-ondemand.yml@project/geosongpu
    with:
      experiment_name: physics_standalone_radcoup
      experiment_action: Validation
      geosongpu_ci_ref: main
